name: mobile_app_shop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/cameradsr.jpg
    - assets/imagens/notbookpro.jpg
    - assets/imagens/fone.jpg  
    - assets/imagens/nintendo.jpg  
    - assets/imagens/smart55.jpg
    - assets/imagens/smatphonex.jpg  

